Update oss docs
MyUNiDAYS/unidays-java pull request #5
Opened 2018-08-17 12:48 UTC by Danny-UKDM

### Description of the Change

Various updates to markdown documentation for reader clarity.

### Benefits

Improved understanding of documentation, conventions, guidelines and conduct. 

### Possible Drawbacks

n/a

### Verification Process

n/a

### Applicable Issues

n/a

2018-08-24 13:37 UTC, jackthorley requested changes

2018-08-24 13:37 UTC, jackthorley commented on .github/ISSUE_TEMPLATE/feature_request.md
>  - A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
This should be `e.g` not `Ex.`

2018-08-24 13:37 UTC, jackthorley commented on .github/contributing.md
> +| Label       | Purpose             |
I feel like the justification on these tables need to just be left aligned. But that's a stylistic decision

2018-08-24 13:37 UTC, jackthorley commented on .github/contributing.md
> +| Label       | Purpose             |
All the tables need looking at in this. They need some consistency.

2018-08-24 19:48 UTC, jackthorley approved these changes

2018-08-27 08:19 UTC, jessicabrentnall approved these changes

2018-08-27 08:21 UTC, merged